[package]
name = "yarr"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
quick-xml = "0.22"
serde = { version = "1.0", features = ["derive"] }
